### ISSUE TITLE
How to use in Github Action?

### ISSUE THREAD

**Issue by renanbastos93** [jpoles1/gopherbadger#14]

**Comment by renanbastos93** [comment]
up

**Comment by dcaponi** [comment]
@renanbastos93 I had luck by adding this to a makefile
```
test:
	go get github.com/jpoles1/gopherbadger
	gopherbadger -md="readme.md" -png=false
```

and adding this to my GH action using this go env runner

```
    - name: Test
      uses: cedrickring/golang-action@master
      with:
        args: make test
```
